### PR TITLE
History Tab

### PR DESCRIPTION
**Pull request by vulcan-dev**
Added a history tab, I believe it's a nice addition.
I'll add a setting to change how many servers will show in the history tab at some point (probably tomorrow)

### CODE REVIEW

**Comment by AsciiJakob** [comment]
Just letting you know that you have two typos in your code.
First one is `server_histroy ` which should be `server_history`. Second one is `draw_histroy_tab` which should be `draw_history_tab`

**Comment by vulcan-dev** [comment]
> Just letting you know that you have two typos in your code.
> First one is `server_histroy ` which should be `server_history`. Second one is `draw_histroy_tab` which should be `draw_history_tab`

Oh alright, appreciate it. I made this typo many times but kept on correcting them, apparently I missed some haha

**Comment by AsciiJakob** [comment]
> 
> 
> > Just letting you know that you have two typos in your code.
> > First one is `server_histroy ` which should be `server_history`. Second one is `draw_histroy_tab` which should be `draw_history_tab`
> 
> Oh alright, appreciate it. I made this typo many times but kept on correcting them, apparently I missed some haha

No worries. 
Additionally, only servers you connect to from the server-list shows up in the history. Servers connected to from the direct connect tab does not.
This can be fixed by also adding the `add_server_to_history` function to the bottom of [the `draw_direct_connect_tab` function](https://github.com/TheHellBox/KISS-multiplayer/blob/de48e98b6b29b3295d5897d0118150a83b2639f0/KISSMultiplayer/lua/ge/extensions/kissui.lua#L463).

**Comment by vulcan-dev** [comment]
I'll do that after I get home, appreciate it once again 👍

**Pull request closed without merging**
